In [19]:
import pandas as pd
import seaborn as sns
import numpy as np

In [20]:
df=sns.load_dataset("titanic")

In [21]:
df['who'].unique()

<ArrowStringArray>
['man', 'woman', 'child']
Length: 3, dtype: str

In [22]:
pd.get_dummies(df['who']).head()

   child    man  woman
0  False   True  False
1  False  False   True
2  False  False   True
3  False  False   True
4  False   True  False

In [23]:
### groupy functions

In [24]:
df=sns.load_dataset("mpg")

In [25]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [26]:
### based on single col

In [32]:
df.groupby('origin').sum()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name
origin,,,,,,,,
europe,1952.4,291,7640.0,5478.0,169631,1175.1,5307,volkswagen 1131 deluxe sedanpeugeot 504audi 10...
japan,2405.6,324,8114.0,6307.0,175477,1277.6,6118,toyota corona mark iidatsun pl510datsun pl510t...
usa,5000.8,1556,61229.5,29167.0,837121,3743.4,18827,chevrolet chevelle malibubuick skylark 320plym...

In [33]:
df[df['origin']=='europe'].shape

(70, 9)

In [34]:
den = 70

In [37]:
num = df[df['origin']=='europe']['mpg'].sum()

In [38]:
num/den

np.float64(27.89142857142857)

In [41]:
df.groupby(['origin','model_year']).sum()

                     mpg  cylinders  displacement  horsepower  weight  \
origin model_year
europe 70          126.0         20         539.0       431.0   11546
       71          115.0         16         380.0       296.0    8096
       72          110.0         20         555.0       398.0   12866
       73          168.0         28         735.0       573.0   16350
       74          162.0         24         559.0       445.0   12836
       75          147.0         24         657.0       537.0   15427
       76          194.0         34         929.0       701.0   20888
       77          117.0         16         394.0       324.0    8555
       78          149.7         29         757.0       595.0   16150
       79          121.8         17         504.0       288.0   10775
       80          335.6         37         938.0       534.0   21132
       81          126.3         18         491.0       230.0   10900
       82           80.0          8         202.0       126.0    4110
japan  70           51.0          8         210.0       183.0    4502
       71          118.0         16         353.0       317.0    7744
       72          121.0         19         497.0       469.0   11502
       73           80.0         17         431.0       394.0    9589
       74          176.0         24         537.0       435.0   12318
       75          110.0         16         441.0       321.0    9213
       76          112.0         18         429.0       306.0    8870
       77          164.5         25         603.0       487.0   13775
       78          237.5         32         858.0       634.0   17770
       79           65.9          8         171.0       130.0    3995
       80          460.2         53        1360.0      1025.0   29774
       81          395.5         52        1290.0       940.0   27230
       82          314.0         36         934.0       666.0   19195
usa    70          336.0        168        7412.0      3673.0   81763
       71          362.0        124        5140.0      2277.0   68032
       72          293.0        124        5062.5      2498.0   66288
       73          436.0        210        9109.0      4252.0  110822
       74          275.0         94        3541.0      1570.0   52550
       75          351.0        128        5068.0      2174.0   70664
       76          427.5        140        5367.0      2431.0   74919
       77          373.0        112        4362.0      2131.0   61596
       78          479.0        132        4786.0      2360.0   69105
       79          540.0        144        5319.0      2517.0   73835
       80          181.4         30        1061.0       533.0   19757
       81          357.9         64        2143.0      1099.0   35035
       82          589.0         86        2859.0      1652.0   52755

                   acceleration  \
origin model_year
europe 70                  82.5
       71                  67.0
       72                  93.5
       73                 115.0
       74                  92.0
       75                  90.5
       76                 128.4
       77                  60.0
       78                  97.4
       79                  73.6
       80                 165.3
       81                  70.0
       82                  39.9
japan  70                  29.5
       71                  65.5
       72                  77.0
       73                  62.5
       74                 106.0
       75                  64.0
       76                  66.3
       77                  97.9
       78                 129.6
       79                  34.4
       80                 208.2
       81                 194.2
       82                 142.5
usa    70                 263.5
       71                 291.5
       72                 253.0
       73                 395.0
       74                 239.5
       75                 327.0
       76                 347.3
       77                 274.3
       78                 342.0
       79                 350.6
       80                 117.6
       81                 208.7
       82                 333.4

                                                                name
origin model_year
europe 70          volkswagen 1131 deluxe sedanpeugeot 504audi 10...
       71          opel 1900peugeot 304fiat 124bvolkswagen model 111
       72          volkswagen type 3volvo 145e (sw)volkswagen 411...
       73          volkswagen super beetlefiat 124 sport coupefia...
       74          audi foxvolkswagen dasheropel mantafiat 128fia...
       75          volkswagen dashervolkswagen rabbitaudi 100lspe...
       76          fiat 131opel 1900renault 12tlvw rabbitvolkswag...
       77          renault 5 gtlvolkswagen rabbit customvolkswage...
       78          volkswagen rabbit custom dieselaudi 5000volvo ...
       79          vw rabbit custommercedes benz 300dpeugeot 504f...
       80          vw rabbitaudi 4000vw rabbit c (diesel)vw dashe...
       81          volkswagen jettarenault 18ipeugeot 505s turbo ...
       82                               volkswagen rabbit lvw pickup
japan  70                          toyota corona mark iidatsun pl510
       71          datsun pl510toyota coronatoyota corolla 1200da...
       72          toyota corona hardtopmazda rx2 coupedatsun 510...
       73             toyota carinadatsun 610maxda rx3toyota mark ii
       74          datsun b210toyota corolla 1200toyota coronadat...
       75          toyota corollatoyota coronadatsun 710honda civ...
       76          honda civicdatsun b-210toyota corollatoyota ma...
       77          honda accord cvccdatsun f-10 hatchbacktoyota c...
       78          mazda glc deluxedatsun b210 gxhonda civic cvcc...
       79                                 maxda glc deluxedatsun 210
       80          toyota corolla terceldatsun 310toyota corona l...
       81          toyota starlethonda civic 1300subarudatsun 210...
       82          mazda glc custom lmazda glc customnissan stanz...
usa    70          chevrolet chevelle malibubuick skylark 320plym...
       71          chevrolet vega 2300ford pintoamc gremlinplymou...
       72          dodge colt hardtopchevrolet vegaford pinto run...
       73          buick century 350amc matadorchevrolet malibufo...
       74          plymouth dusterford maverickamc hornetchevrole...
       75          plymouth valiant customchevrolet novamercury m...
       76          capri iidodge coltchevrolet chevelle malibu cl...
       77          buick opel isuzu deluxeplymouth arrow gschevro...
       78          ford fiestaoldsmobile cutlass salon broughamdo...
       79          pontiac lemans v6mercury zephyr 6ford fairmont...
       80          chevrolet chevettechevrolet citationford fairm...
       81          plymouth reliantbuick skylarkdodge aries wagon...
       82          chevrolet cavalierchevrolet cavalier wagonchev...