In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/Users/apple/Downloads/extracted_data.csv")

In [3]:
df.head()

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
0,701.0,49,38,37,99,Yes,Bangalore,Day 1
1,807.0,73,14,81,81,Yes,Bangalore,Day 2
2,743.0,23,75,38,40,Yes,Bangalore,Day 3
3,347.0,85,82,74,32,Yes,Bangalore,Day 4
4,275.0,100,10,83,43,Yes,Bangalore,Day 5

In [4]:
df.describe()

            Sales       Units  Transactions  Gross Profits  Customers
count   27.000000   28.000000     28.000000       28.00000  28.000000
mean   489.259259   84.321429     52.464286       52.50000  52.857143
std    260.817884  172.220155     26.939551       23.72606  27.055107
min    105.000000   11.000000     10.000000       14.00000  11.000000
25%    265.000000   31.500000     31.750000       32.25000  31.000000
50%    453.000000   54.000000     52.000000       48.50000  55.000000
75%    722.000000   74.000000     75.750000       73.25000  73.500000
max    962.000000  953.000000     97.000000       87.00000  99.000000

In [5]:
df.describe(include='object')

/var/folders/n9/klj9bs6j6h175l1xsqhs40n40000gn/T/ipykernel_3186/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       Promotions(Yes/No)   Location   Days
count                  28         28     28
unique                  2          4      7
top                   Yes  Bangalore  Day 1
freq                   18          7      4

In [6]:
df.describe(include='all')

,Sales,Units,Transactions,Gross Profits,Customers,Promotions(Yes/No),Location,Days
count,27.000000,28.000000,28.000000,28.00000,28.000000,28,28,28
unique,NaN,NaN,NaN,NaN,NaN,2,4,7
top,NaN,NaN,NaN,NaN,NaN,Yes,Bangalore,Day 1
freq,NaN,NaN,NaN,NaN,NaN,18,7,4
mean,489.259259,84.321429,52.464286,52.50000,52.857143,NaN,NaN,NaN
std,260.817884,172.220155,26.939551,23.72606,27.055107,NaN,NaN,NaN
min,105.000000,11.000000,10.000000,14.00000,11.000000,NaN,NaN,NaN
25%,265.000000,31.500000,31.750000,32.25000,31.000000,NaN,NaN,NaN
50%,453.000000,54.000000,52.000000,48.50000,55.000000,NaN,NaN,NaN
75%,722.000000,74.000000,75.750000,73.25000,73.500000,NaN,NaN,NaN
max,962.000000,953.000000,97.000000,87.00000,99.000000,NaN,NaN,NaN